---
- name: Install common packages from apt
  apt: pkg={{item}} state=installed update_cache=yes
  sudo: True
  with_items:
    - git
    - make
    - python-pip
    - python-dev
    - curl
    - zip
    - unzip
    - awscli

- name: Install global python modules
  pip: name={{item}}
  sudo: True
  with_items:
    - awscli
    - virtualenv
    - pexpect

- name: Create aws crendentials directory
  file: path={{home}}/.aws state=directory

- name: Create aws credentials
  template: src=config.j2 dest={{home}}/.aws/config

- name: Download eBird data from S3
  command: "aws s3 cp s3://birt-data/{{ebird_archive_name}} {{ home }}/{{ebird_archive_name}}"
  args:
    creates: "{{ home }}/{{ebird_archive_name}}"
  become_user: ubuntu
  register: data_downloaded

- file: path="{{home}}/ebird_data" state="directory"

- name: Extract eBird data
  unarchive: src="{{home}}/{{ebird_archive_name}}" dest="{{home}}/ebird_data" copy=no
  when: data_downloaded.changed

- find: paths="{{home}}/ebird_data" patterns="core-covariates.csv" recurse=yes
  register: covariate_files

- find: paths="{{home}}/ebird_data" patterns="checklists.csv" recurse=yes
  register: checklist_files

- name: Copy birt consumer code
  copy: src=birt-consumer dest="{{home}}/"

- name: Install requirements
  pip: requirements="{{home}}/birt-consumer/requirements.txt" virtualenv="{{home}}/birt-consumer-env"

- name: Import bird taxonomy collection
  command: "{{home}}/birt-consumer-env/bin/python {{home}}/birt-consumer/birt_consume.py --type Taxonomy {{home}}/birt-consumer/tests/data/taxonomy.csv"

- name: Import bird sightings checklist data
  command: "{{home}}/birt-consumer-env/bin/python {{home}}/birt-consumer/birt_consume.py --type Checklist {{ item.path }}"
  with_items: checklist_files.files
  #wait up to 1 day
  async: 86400
  poll: 0
  register: checklist_async_results

- name: Wait for import to finish
  async_status:
    jid: "{{item.ansible_job_id}}"
  with_items: checklist_async_results.results
  register: checklist_async_poll
  until: checklist_async_poll.finished
  #wait up to 1 day
  retries: 144
  delay: 600

- name: Start import bird sightings covariate data
  command: "{{home}}/birt-consumer-env/bin/python {{home}}/birt-consumer/birt_consume.py --type Core {{ item.path }}"
  with_items: covariate_files.files
  #wait up to 1 day
  async: 86400
  poll: 0
  register: covariate_async_results

- name: Wait for import to finish
  async_status:
    jid: "{{item.ansible_job_id}}"
  with_items: covariate_async_results.results
  register: covariate_async_poll
  until: covariate_async_poll.finished
  #wait up to 1 day
  retries: 144
  delay: 600

- name: Create birt indexes
  expect:
    command: "{{home}}/birt-consumer-env/bin/python {{home}}/birt-consumer/birt_ensure_index.py"
    responses:
      # This will lock the database. Are you sure?
      \[y/N\]: "Y"
    timeout: 3000
