---
- name: Install common packages from apt
  apt: pkg={{item}} state=installed update_cache=yes
  sudo: True
  with_items:
    - git
    - make
    - python-pip
    - python-dev
    - curl
    - zip
    - unzip
    - awscli

- name: Install global python modules
  pip: name={{item}}
  sudo: True
  with_items:
    - awscli
    - virtualenv

- name: Create aws crendentials directory
  file: path={{home}}/.aws state=directory

- name: Create aws credentials
  template: src=config.j2 dest={{home}}/.aws/config

- name: Download eBird data from S3
  command: "aws s3 cp s3://birt-data/{{ebird_archive_name}} {{ home }}/{{ebird_archive_name}}"
  args:
    creates: "{{ home }}/{{ebird_archive_name}}"
  become_user: ubuntu
  register: data_downloaded

- file: path="{{home}}/ebird_data" state="directory"

- name: Extract eBird data
  unarchive: src="{{home}}/{{ebird_archive_name}}" dest="{{home}}/ebird_data" copy=no
  when: data_downloaded.changed

- find: paths="{{home}}/ebird_data" patterns="core-covariates.csv" recurse=yes
  register: covariate_files

- find: paths="{{home}}/ebird_data" patterns="checklists.csv" recurse=yes
  register: checklist_files

- name: Copy birt consumer code
  copy: src=birt-consumer dest="{{home}}/"

- name: Install requirements
  pip: requirements="{{home}}/birt-consumer/requirements.txt" virtualenv="{{home}}/birt-consumer-env"

- name: Import bird taxonomy collection
  command: "{{home}}/birt-consumer-env/bin/python {{home}}/birt-consumer/birt_consume.py --type Taxonomy {{home}}/birt-consumer/tests/data/taxonomy.csv"

- name: Import bird sightings checklist data
  command: "{{home}}/birt-consumer-env/bin/python {{home}}/birt-consumer/birt_consume.py --type Checklist {{ item.path }}"
  with_items: checklist_files.files

- name: Import bird sightings covariate data
  command: "{{home}}/birt-consumer-env/bin/python {{home}}/birt-consumer/birt_consume.py --type Core {{ item.path }}"
  with_items: covariate_files.files

- name: Create birt indexes
  command: "{{home}}/birt-consumer-env/bin/python {{home}}/birt-consumer/birt_ensure_index.py"

- name: Dump database
  command: mongodump

- name: Backup the database to S3
  command: "aws s3 cp --recursive dump s3://birt-data/dump"
